version: '2'

services:
  libretime-postgres:
    image: postgres:9.3-alpine
    container_name: libretime-postgres
    restart: always
    privileged: true

    environment:
      - POSTGRES_PASSWORD=libretime
      - POSTGRES_USER=libretime
      - PGDATA=/postgres_data

    volumes:
      - ./postgresql:/postgres_data
      - /etc/localtime:/etc/localtime:ro

    networks:
      - libretime-internal

    ports:
      # Postgre port mapped to non-standard port (for external admin access) - Internal access is via the internal docker network
      - 5433:5432

  libretime-rabbitmq:
    image: rabbitmq:3.6-alpine
    container_name: libretime-rabbitmq
    restart: always
    privileged: true

    environment:
      - RABBITMQ_DEFAULT_USER=libretime
      - RABBITMQ_DEFAULT_PASS=libretime
      - "RABBITMQ_DEFAULT_VHOST=/libretime"

    volumes:
      - /etc/localtime:/etc/localtime:ro

    networks:
      - libretime-internal

  libretime-core:
    # Uncomment to build locally
    # build: .

    # Comment out if you want to use the local build rather than what's on docker-hub.
    image: bushrangers/ubuntu-multicontainer-libretime

    container_name: libretime-core
    restart: always
    privileged:  true

    ports:
      # Icecast Default Port
      - 8000:8000

      # Master & Show Source Inputs:
      - 8001:8001
      - 8002:8002

      # This is the web UI Port (proxy pass to this, change to 80:80 if you want to access directly in the browser without a reverse proxy)
      - 8882:80

    environment:

      #### NOTE: ####
      #
      # For detailed configuration, please edit the `config/airtime/airtime.conf` file once the container has started for the first time.
      # The configuration variables here will over-write your airtime.conf file on the server when booting.
      #
      ########################################################################################

      # Don't change these unless you change their values in the `libretime-rabbitmq` block.
      - RABBITMQ_DEFAULT_VHOST=/libretime
      - RABBITMQ_DEFAULT_USER=libretime
      - RABBITMQ_DEFAULT_PASS=libretime

      - POSTGRES_USER=libretime
      - POSTGRES_PASSWORD=libretime
      - POSTGRES_DB_NAME=libretime

      # Leave as default if you're not planning on using AWS S3, otherwise set your AWS credentials to auto-upload your recordings etc to S3.
      - "AWS_S3_API_KEY=0"
      - "AWS_S3_API_SECRET=0"
      - "AWS_S3_BUCKET_NAME=0"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/icecast.xml:/etc/icecast2/icecast.xml
      
      # This structure has not yet been renamed in the fork of libretime from airtime.
      - ./config/airtime:/etc/airtime

      # NB: Libretime will create some directories in this location (for user uploads, recorded podcasts etc)
      # Only change the `/localmedia` part of this directive to the location of your media files..
      - /localmusic:/external-media

    networks:
      - libretime-internal
      - libretime

networks:

  # You will need to run `docker network create libretime` for this to work properly before standing up the container..
  libretime:
    external: true

  libretime-internal:
    driver: bridge
